variables:
  TOKEN: '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'
  GITHUB_ACCOUNT: 'withmonumental'
  REPO: 'docs.git'

stages:
  - build
  - publish

build stage:
  stage: build
  script:
    - yarn install
    - NODE_OPTIONS=--max_old_space_size=4096 yarn build
  artifacts:
    paths:
      - public

publish stage:
  stage: publish
  script:
    - pwd
    - echo $CI_COMMIT_SHORT_SHA
    - echo $CI_PROJECT_DIR
    - ls -l $CI_PROJECT_DIR/
    - cd public
    - git clone https://$GITHUB_ACCOUNT:$TOKEN@github.com/$GITHUB_ACCOUNT/$REPO
    - git pull remote main
    - git add -A
    - git commit -m "deploy $CI_COMMIT_SHORT_SHA"
    - git remote remove origin
    - git remote add origin https://$GITHUB_ACCOUNT:$TOKEN@github.com/$GITHUB_ACCOUNT/$REPO
    - git push origin HEAD:main
