image: node:10.22.0
pages:
  cache:
    paths:
      - node_modules/

  script:
    - yarn install # npm install
    - NODE_OPTIONS=--max_old_space_size=4096 yarn run build
  artifacts:
    paths:
      - public
  only:
    - master

      stages:
  - build
  - deploy
