export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"Home","i":"home","I":1},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"Slide page","i":"slides","I":1},["/slides","/slides.md"]],
  ["v-65752393","/guides/artist.html",{"y":"a","t":"Artist","I":1},["/guides/artist","/guides/artist.md"]],
  ["v-7d1199fb","/guides/aws.html",{"y":"a","t":"AWS","I":1},["/guides/aws","/guides/aws.md"]],
  ["v-50a17429","/guides/ban.html",{"y":"a","t":"Ban principles","I":1},["/guides/ban","/guides/ban.md"]],
  ["v-5b51f1aa","/guides/collector.html",{"y":"a","t":"Collector","I":1},["/guides/collector","/guides/collector.md"]],
  ["v-15769cfc","/guides/faq.html",{"y":"a","t":"Frequently Asked Questions","I":1},["/guides/faq","/guides/faq.md"]],
  ["v-ff762602","/guides/",{"y":"a","t":"Guides","I":1},["/guides/index.html","/guides/README.md"]],
  ["v-6009c78e","/guides/right_to_be_forgotten.html",{"y":"a","t":"Right to be forgotten","I":1},["/guides/right_to_be_forgotten","/guides/right_to_be_forgotten.md"]],
  ["v-0d1ea06e","/guides/royalties.html",{"y":"a","t":"Royalties","I":1},["/guides/royalties","/guides/royalties.md"]],
  ["v-5d4736a2","/guides/smartContracts.html",{"y":"a","t":"Edition types","I":1},["/guides/smartContracts","/guides/smartContracts.md"]],
  ["v-7c2cbc3c","/guides/snb_artwork.html",{"y":"a","t":"Selling and Buying Artwork","I":1},["/guides/snb_artwork","/guides/snb_artwork.md"]],
  ["v-d6049b5a","/guides/spaceManager.html",{"y":"a","t":"Space Manager","I":1},["/guides/spaceManager","/guides/spaceManager.md"]],
  ["v-5d2d3d96","/guides/spaceSubscription.html",{"y":"a","t":"Space Subscription","I":1},["/guides/spaceSubscription","/guides/spaceSubscription.md"]],
  ["v-72ffaf0c","/legal/code_of_conduct.html",{"y":"a","t":"Code of conduct","I":1},["/legal/code_of_conduct","/legal/code_of_conduct.md"]],
  ["v-2376ec0e","/legal/cookies.html",{"y":"a","t":"Cookie notice","I":1},["/legal/cookies","/legal/cookies.md"]],
  ["v-2e70cf81","/legal/privacy_policy.html",{"y":"a","t":"Privacy policy","I":1},["/legal/privacy_policy","/legal/privacy_policy.md"]],
  ["v-f0afee62","/legal/",{"y":"a","t":"Legal","I":1},["/legal/index.html","/legal/README.md"]],
  ["v-2f6398d2","/legal/tac.html",{"y":"a","t":"Terms and Conditions","I":1},["/legal/tac","/legal/tac.md"]],
  ["v-8ba935d4","/original/disable.html",{"y":"a","t":"Disabling layout and features","i":"config","I":1},["/original/disable","/original/disable.md"]],
  ["v-fe95088e","/original/encrypt.html",{"y":"a","t":"Encryption Article","i":"lock","I":1},["/original/encrypt","/original/encrypt.md"]],
  ["v-28a50fc5","/original/markdown.html",{"y":"a","t":"How to install and set up MetaMask","i":"markdown","I":1},["/original/markdown","/original/markdown.md"]],
  ["v-888aeb72","/started/commissionAndFees.html",{"y":"a","t":"Commission and fees","I":1},["/started/commissionAndFees","/started/commissionAndFees.md"]],
  ["v-1b941618","/started/introduction.html",{"y":"a","t":"Introduction","I":1},["/started/introduction","/started/introduction.md"]],
  ["v-2525b9c7","/started/",{"y":"a","t":"Get Started","I":1},["/started/index.html","/started/README.md"]],
  ["v-b8f33ca2","/started/register.html",{"y":"a","t":"Join Monumental","I":1},["/started/register","/started/register.md"]],
  ["v-4904cd43","/started/roles.html",{"y":"a","t":"Roles and scope","I":1},["/started/roles","/started/roles.md"]],
  ["v-7fff4eb6","/started/spaces.html",{"y":"a","t":"Space","I":1},["/started/spaces","/started/spaces.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":"","I":1},["/404"]],
  ["v-1ad9f4b6","/original/",{"y":"p","t":"Original","I":1},["/original/index.html"]],
]
