export const data = JSON.parse("{\"key\":\"v-02528f32\",\"path\":\"/guides/sellingAndBuyingArtwork.html\",\"title\":\"Selling and Buying Artwork\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Selling and Buying Artwork\",\"pageInfo\":false,\"order\":3,\"author\":\"Monumental Team\",\"date\":\"2020-01-01T00:00:00.000Z\",\"category\":[\"Guide\"],\"tag\":[\"Page config\",\"Guide\"],\"sticky\":true,\"star\":true,\"copyright\":false,\"footer\":\"Monumental | Copyright © 2023\",\"description\":\"All authorised participants with a valid digital wallet and available funds are allowed trending artworks on Monumental. Not only Monumental gives access to first and second mar...\"},\"headers\":[{\"level\":2,\"title\":\"Becoming an user on Monumental\",\"slug\":\"becoming-an-user-on-monumental\",\"link\":\"#becoming-an-user-on-monumental\",\"children\":[]},{\"level\":2,\"title\":\"Sale Smart Contracts generation\",\"slug\":\"sale-smart-contracts-generation\",\"link\":\"#sale-smart-contracts-generation\",\"children\":[]},{\"level\":2,\"title\":\"Available States during a Selling Process\",\"slug\":\"available-states-during-a-selling-process\",\"link\":\"#available-states-during-a-selling-process\",\"children\":[{\"level\":3,\"title\":\"Definitions\",\"slug\":\"definitions\",\"link\":\"#definitions\",\"children\":[]},{\"level\":3,\"title\":\"Different artwork’s states during a Fixed Price Sale\",\"slug\":\"different-artwork-s-states-during-a-fixed-price-sale\",\"link\":\"#different-artwork-s-states-during-a-fixed-price-sale\",\"children\":[]},{\"level\":3,\"title\":\"Different artwork’s states during a Timed Auction Sale:\",\"slug\":\"different-artwork-s-states-during-a-timed-auction-sale\",\"link\":\"#different-artwork-s-states-during-a-timed-auction-sale\",\"children\":[]},{\"level\":3,\"title\":\"No bid done yet / Artwork displayed under “JUST LISTED” on the portal page\",\"slug\":\"no-bid-done-yet-artwork-displayed-under-just-listed-on-the-portal-page\",\"link\":\"#no-bid-done-yet-artwork-displayed-under-just-listed-on-the-portal-page\",\"children\":[]},{\"level\":3,\"title\":\"Auction is on : Bid made / Artwork displayed under “LIVE AUCTIONS” on the portal page\",\"slug\":\"auction-is-on-bid-made-artwork-displayed-under-live-auctions-on-the-portal-page\",\"link\":\"#auction-is-on-bid-made-artwork-displayed-under-live-auctions-on-the-portal-page\",\"children\":[]},{\"level\":3,\"title\":\"Auction is over : Time period is ended / the artwork is displayed under “JUST SOLD” on the portal page\",\"slug\":\"auction-is-over-time-period-is-ended-the-artwork-is-displayed-under-just-sold-on-the-portal-page\",\"link\":\"#auction-is-over-time-period-is-ended-the-artwork-is-displayed-under-just-sold-on-the-portal-page\",\"children\":[]}]}],\"readingTime\":{\"minutes\":9.58,\"words\":2874},\"filePathRelative\":\"guides/sellingAndBuyingArtwork.md\",\"localizedDate\":\"January 1, 2020\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
